import { createTheme, alpha } from '@mui/material/styles';
// Enhanced C4R color palette
const c4rColors = {
  primary,
    dark,
    light,
    lighter,
    contrastText,
  },
  secondary,
    dark,
    light,
    lighter,
    contrastText,
  },
  accent,
    dark,
    light,
    lighter,
    contrastText,
  },
  // Extended semantic colors
  success,
  warning,
  error,
  info,
  // Neutral grays (Tailwind-based)
  gray,
    100,
    200,
    300,
    400,
    500,
    600,
    700,
    800,
    900,
  },
};

// Create enhanced theme with better component overrides
const createC4RTheme = (options= {}) => {
  const baseTheme = createTheme({
    palette,
      primary,
      secondary,
      success,
        dark,
        light,
        contrastText,
      },
      warning,
        dark,
        light,
        contrastText,
      },
      error,
        dark,
        light,
        contrastText,
      },
      info,
        dark,
        light,
        contrastText,
      },
      grey,
      background,
        paper,
      },
      text,
        secondary,
        disabled,
      },
      divider,
    },

    typography,
        'GeneralSans-Regular',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Arial',
        'sans-serif',
      ].join(','),
      
      // Enhanced typography with better line heights and spacing
      h1,
        fontWeight,
        lineHeight,
        fontFamily, General Sans, sans-serif',
        letterSpacing,
      },
      h2,
        fontWeight,
        lineHeight,
        fontFamily, General Sans, sans-serif',
        letterSpacing,
      },
      h3,
        fontWeight,
        lineHeight,
        fontFamily, General Sans, sans-serif',
      },
      h4,
        fontWeight,
        lineHeight,
        fontFamily, General Sans, sans-serif',
      },
      body1,
        fontWeight,
        lineHeight,
      },
      body2,
        fontWeight,
        lineHeight,
      },
      caption,
        fontWeight,
        lineHeight,
      },
      button,
        fontWeight,
        textTransform,
        letterSpacing,
      },
    },

    shape,
    },

    spacing,

    shadows,
      '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
      '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
      '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
      '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      '0 25px 50px -12px rgb(0 0 0 / 0.25)',
      // ... continue Tailwind shadow system
      ...Array(18).fill('0 25px 50px -12px rgb(0 0 0 / 0.25)'),
    ],

    ...options,
  });

  // Enhanced component overrides
  return createTheme(baseTheme, {
    components,
            textTransform,
            fontWeight,
            fontSize,
            padding,
            transition, 0, 0.2, 1)',
            boxShadow,
            '&:hover': {
              boxShadow,
            },
            '&:focus': {
              outline, 0.5)}`,
              outlineOffset,
            },
          },
          contained,
            '&:hover': {
              boxShadow,
            },
            '&:active': {
              boxShadow,
            },
          },
          outlined,
            '&:hover': {
              borderWidth,
            },
          },
        },
        variants,
            style,
              color,
              '&:hover': {
                backgroundColor,
              },
              '&:disabled': {
                backgroundColor, 0.5),
                color,
              },
            },
          },
          {
            props,
            style,
              color,
              '&:hover': {
                backgroundColor,
              },
            },
          },
          {
            props,
            style,
              color,
              '&:hover': {
                backgroundColor,
              },
            },
          },
          {
            props,
            style,
              color,
              border,
              '&:hover': {
                backgroundColor, 0.8),
              },
            },
          },
        ],
      },

      // Enhanced Card styling
      MuiCard,
            border,
            boxShadow,
            transition, 0, 0.2, 1)',
            '&:hover': {
              boxShadow,
              transform)',
            },
          },
        },
        variants,
            style,
              '&:hover': {
                boxShadow,
              },
            },
          },
          {
            props,
            style,
              border,
              '&:hover': {
                borderColor,
                transform,
              },
            },
          },
        ],
      },

      // Enhanced TextField
      MuiTextField,
              transition, 0, 0.2, 1)',
              '& fieldset': {
                borderColor,
                borderWidth,
              },
              '&:hover fieldset': {
                borderColor,
              },
              '&.Mui-focused fieldset': {
                borderColor,
                borderWidth,
              },
              '&.Mui-error fieldset': {
                borderColor,
              },
            },
            '& .MuiInputLabel-root': {
              '&.Mui-focused': {
                color,
              },
            },
          },
        },
      },

      // Enhanced Dialog
      MuiDialog,
            boxShadow,
          },
        },
      },

      // Enhanced Paper
      MuiPaper,
          },
        },
        variants,
            style),
              border,
              boxShadow,
            },
          },
        ],
      },

      // Enhanced Alert
      MuiAlert,
            border,
          },
          standardSuccess, 0.1),
            color,
            '& .MuiAlert-icon': {
              color,
            },
          },
          standardWarning, 0.1),
            color,
            '& .MuiAlert-icon': {
              color,
            },
          },
          standardInfo, 0.1),
            color,
          },
        },
      },

      // Enhanced Chip
      MuiChip,
            fontWeight,
          },
          filled,
              color,
            },
            '&.MuiChip-colorSecondary': {
              backgroundColor,
              color,
            },
          },
        },
      },

      // Enhanced Tab styling
      MuiTabs,
            height,
            borderRadius,
          },
        },
      },

      MuiTab,
            fontWeight,
            fontSize,
            '&.Mui-selected': {
              color,
            },
          },
        },
      },

      // Tooltip enhancements
      MuiTooltip,
            fontSize,
            borderRadius,
            padding,
          },
          arrow,
          },
        },
      },
    },
  });
};

export { createC4RTheme, c4rColors };
export default createC4RTheme();