/*import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
*/
import localFont from "next/font/local";
import Script from 'next/script';

import "./styles/tailwind-preflight.css";

// import "./styles/normalize.css";
// import "./globals.css";

import "./styles/globals.css";
// import "./styles/normalize.css";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
// import CssBaseline from '@mui/material/CssBaseline';

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


// const generalSansVariable = localFont({
//   src: "./fonts/GeneralSans-Variable.woff",
//   variable: "--font-general-sans-variable",
//   weight: "100 900",
// });
// const generalSansVariableItalic = localFont({
//   src: "./fonts/GeneralSans-VariableItalic.woff",
//   variable: "--font-general-sans-variable-italic",
//   weight: "100 900",
// });
const generalSansSemiBold = localFont({
  src: "./fonts/GeneralSans-Semibold.woff",
  variable: "--font-general-sans-semi-bold",
  weight: "100 900",
});

const generalSansVariable = localFont({
  src: "./fonts/GeneralSans-Variable.woff",
  variable: "--font-general-sans-variable",
  weight: "100 900",
});

// General sans medium
const generalSansMedium = localFont({
  src: "./fonts/GeneralSans-Medium.woff",
  variable: "--font-general-sans-medium",
  weight: "100 900",
});

export const metadata = {
  title: "Deduce the Number Rule",
  description: "Deduce the Number Rule",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>

      <AppRouterCacheProvider>
        {/* <CssBaseline /> */}
        <body className={`${generalSansSemiBold.variable} ${generalSansVariable.variable} ${generalSansMedium.variable}`}>
           {/* Google Analytics Script */}
          <Script
            async
            src="https://www.googletagmanager.com/gtag/js?id=G-QR2FTRGC9D"
            strategy="afterInteractive"
          />
          <Script
            id="google-analytics"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html: `
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', 'G-QR2FTRGC9D');
              `,
            }}
          />
          {children}
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
